### PR TITLE
Fix hash value merge

### PR DESCRIPTION
**Pull request by mbland**
@adelevie I noticed this while working on creating usage examples for the docs. :-)

### CODE REVIEW

**Comment by mbland** [comment]
@adelevie Ping... I've also done a bunch of work in this PR to improve the Gem structure, add license notices, and refactor to make Code Climate happy. Can cherry-pick into a new PR or two if this is too much.

**Comment by mbland** [comment]
@adelevie Ping... Hope to get this guy in there sometime soon, too. :-)

**Comment by mbland** [comment]
Ah, realized I needed to `git rebase -i origin/master` and `git push -f` to clean up this PR. PTAL?

**Comment by adelevie** [comment]
Tough for me to know what all the code is doing. It _seems_ fine to me, and the test makes sense.

**Comment by mbland** [comment]
Yeah, the test is the key thing; I added some refactoring commits thanks to the Code Climate feedback. ;-) Basically, the bug was that the hash being merged into (lhs, or left-hand-side) was having its values overwritten with data from the other hash (rhs, or right-hand-side) even when the types didn't match. This PR fixes the bug.

**Pull request merged**
