### PR TITLE
filter-yaml-files executable

### PR DESCRIPTION
**Pull request by mbland**
To see a preview of how this would work in the Hub or other data import scripts: [18F/hub/import-public branch](https://github.com/18F/hub/compare/import-public?expand=1)

@afeld @gboone @adelevie Comments and improvements welcome as always.

### CODE REVIEW

**Comment by adelevie** [comment]
LGTM except for one small nit:

- perhaps `DATA_DIR` should be prefixed with something for a clearer namespace?

**Comment by mbland** [comment]
Hey @adelevie, did you mean `OUTPUT_DIR`? What if I prefixed the local constants with `_` or something?

**Comment by adelevie** [comment]
Well turns out I was wrong as `DATA_DIR` is only used in the bash command example. Nevertheless, `OUTPUT_DIR` sounds pretty generic and should maybe namespaced. I think a word/name would be better than  an `_`.

**Comment by mbland** [comment]
@adelevie Done, even in the README. PTAL?

**Comment by adelevie** [comment]
What's PTAL?

**Comment by mbland** [comment]
PTAL == Please Take Another Look. :-)

**Comment by adelevie** [comment]
A Google-ism? :)

**Comment by adelevie** [comment]
I just PTAL'd and it LGTM.

**Comment by mbland** [comment]
I always thought LGTM was a Google-ism too! ;-) Care to merge, or would you
prefer I did?

**Comment by adelevie** [comment]
SGTM :)

**Pull request merged**
